"""atualizacao de  Orde_hoje

Revision ID: e023f1875dd8
Revises: 824e09562075
Create Date: 2025-03-05 17:04:21.693608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e023f1875dd8'
down_revision: Union[str, None] = '824e09562075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_hoje', sa.Column('day', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_hoje', 'day')
    # ### end Alembic commands ###
